# Site settings
title: Simaster
subtitle: "Kumpulan File Simaster Tersedia Disini"
header-img: assets/images/post.png
image: assets/images/post.png
copyright_name: Simaster
description: "Kumpulan File Simaster Tersedia Disini."
url: "https://clashmwns.com"
author: Muhammad Yusuf
twitter_username: mwnsofficial
github_username: mwnsofficial
youtube_username: mwnsofficial
facebook_username: myarachma92
email_username: myarachma92@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 6
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
