title: simaster
repository: mwnsofficial/simaster
author: Muhammad Yusuf

collections:
  authors:
    output: true

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - some-other-jekyll-plugin
  - jekyll-sitemap
  - jekyll-feed
