# ini jalur repository blog ini
repository: mwnsofficial/simaster

url: https://www.mwns.eu.org

# bisa multifungsi selain web bisa juga menampilkan pdf
output: web

# optimasi search engine google
site_title: Semua file simaster tersedia disini.

# ini tempat titik edit cepat pada blog
github_editme_path: mwnsofficial/simaster/blob/main/

# ini tempat titik edit cepat pada blog
# gitlab_editme_path: 

# khusus analisa google
google_analytics: 

# khusus adsense js
google_adsense: ca-pub-1794381705838564

# alamat menampilkan web
host: 127.0.0.1

# port menampilkan web
port: 4000

exclude:
  - .idea/
  - .gitignore
  - vendor

feedback_subject_line: mwns

feedback_email: myarachma92@gmail.com

# feedback_disable: true

# feedback_text: "Need help?"

# feedback_link: "http://helpy.io/"

highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      # if you don't want to use Commento.io and just hide comments, change true to false wherever you see the comments property
      search: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      # if you don't want to use Commento.io and just hide comments, change true to false wherever you see the comments property
      search: true

# ini jalur deskripsi sitemap.xml
description: "Semua file simaster tersedia disini."

# needed for sitemap.xml file only
# url: http://www.clashmwns.com
# baseurl: /mwns


github: [metadata]


plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - some-other-jekyll-plugin
  - jekyll-sitemap
